batch_size: 64
cheat: false
checkpoint_path: checkpoints
cond: true
data_path_train: dataset/datasetsplits/train.txt
data_path_val: dataset/datasetsplits/val.txt
device: mps
dim_model: 128
dropout_p: 0.1
embedding: true
l1_lw: 1.0
learning_rate: 5.0e-05
log_path: logs
lr_decay: 1.0
maxemg: 1.0
modelname: transf
name: 10kg
num_encoder_layers: 8
num_epochs: 1000
num_heads: 16
num_workers: 0
percent: 1.0
predemg: 'True'
seed: 100
shifted: true
step: 30
weight: 10kg
resume: # /Users/mesrwi/kitech/project_skl/mia_transformer/checkpoints/17keypoints/miatransformer_best_model.pth